server:
  port: 8090

spring:
  application:
    name: stock
  jpa:
    database: mysql
    show-sql: true
    properties:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/stockdb
    username: root
    password: Oguzhan.6489